# .travis.yml
dist: trusty
sudo: required
language: node_js

node_js:
  - "7"

cache:
  directories:
    - "node_modules"

install:
 - wget https://github.com/cnotv/cnotv-framework/
 - npm install

script:
 - npm run build

deploy:
  provider: script
  skip_cleanup: true
  script: deploy.sh
  on:
    branch: develop